"""added profile pic url to users model

Revision ID: 53f2b26173c3
Revises: 00f6abb42347
Create Date: 2022-08-10 20:56:15.000552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f2b26173c3'
down_revision = '00f6abb42347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    # ### end Alembic commands ###
