"""added month and year and day to spendings

Revision ID: 65c0aae13aad
Revises: d2e689779cb8
Create Date: 2022-09-07 22:04:04.398741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c0aae13aad'
down_revision = 'd2e689779cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spendings', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('spendings', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('spendings', sa.Column('day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spendings', 'day')
    op.drop_column('spendings', 'year')
    op.drop_column('spendings', 'month')
    # ### end Alembic commands ###
