"""added annual_income to users table

Revision ID: 7ef0ba040906
Revises: ffdc0a98111c
Create Date: 2022-08-02 15:11:20.203950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef0ba040906'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('annual_income', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'annual_income')
    # ### end Alembic commands ###
